### ISSUE TITLE
FreshTinyIoC.TinyIoCResolutionException - Resolve failed: ContactListPageModel

### ISSUE THREAD

**Issue by sayaleepote** [bitzblitz/myCRM#1]
I get this error :
**FreshTinyIoC.TinyIoCResolutionException - Resolve failed: ContactListPageModel**
when I try to run the App on ios using xamarin studio. It occurs at runtime and crashes the app on start. Any idea what is causing this? I even tried to build the whole project from scratch following the video tutorial. But I'm facing the same issue.

**Comment by bitzblitz** [comment]
Unfortunately I don't have a Mac to try this on. I have verified that it works on Android and UWP. The IoC does appear to have a problem in the Windows 8.1 target which may be similar to your problem. This is part of the FreshMvvm internals so I'm not sure why it is not working. I have updated the packages in this latest check-in, but I doubt it will help.

**Comment by sayaleepote** [comment]
Issue resolved. It was a linker issue in iOS. Changed the settings and the code works fine now. Thanks.
